id: '1743357707824'
  alias: Detector de Presença (Ligar)
  description: Liga a lampada se presença detectada
  triggers:
  - entity_id:
    - sensor.presenca_detectada
    from: Presença Não Detectada
    to: Precença Detectada
    trigger: state
  conditions: []
  actions:
  - action: switch.turn_on
    metadata: {}
    data: {}
    target:
      entity_id: switch.lampada_2
  mode: single
- id: '1745186830191'
  alias: Dimmer
  description: Configura Brilho baseado em um valor alvo
  triggers:
  - entity_id: sensor.lux
    trigger: state
  conditions:
  - condition: numeric_state
    entity_id: sensor.lux
    above: 0
  actions:
  - target:
      entity_id: number.brilho
    data:
      value: "{% if states(light_sensor)|int > maxB %}\n  0\n{% else %}\n  {{ (( slope
        * states(light_sensor)|int ) + constant)|round }}\n{% endif %}\n"
    action: number.set_value
  variables:
    light_sensor: sensor.lux
    maxB: 400
    minB: 0
    light_value_1: 0
    light_value_2: 100
    light1: '{{ light_value_1 * 1 }}'
    light2: '{{ light_value_2 * 1 }}'
    slope: '{{ ( light1 - light2 ) / ( maxB - minB ) }}'
    constant: '{{ light1 - ( slope * maxB ) }}'
  mode: single
- id: '1745710625710'
  alias: Sensor de Presença (Desligar)
  description: Desliga a lampada se presença não detectada
  triggers:
  - entity_id:
    - sensor.presenca_detectada
    to: Presença Não Detectada
    trigger: state
    from: Presença Detectada
    for:
      hours: 0
      minutes: 3
      seconds: 0
  conditions: []
  actions:
  - action: switch.turn_off
    metadata: {}
    data: {}
    target:
      entity_id: switch.lampada_2
  mode: single
- id: '1747447570318'
  alias: Climatização
  description: ''
  triggers:
  - trigger: state
    entity_id:
    - sensor.temperatura
    - input_number.temperatura_alvo
  conditions: []
  actions:
  - choose:
    - conditions:
      - condition: numeric_state
        entity_id: sensor.temperatura
        above: input_number.temperatura_alvo
        below: 51
      sequence:
      - action: switch.turn_on
        metadata: {}
        data: {}
        target:
          entity_id: switch.climatizacao
    - conditions:
      - condition: numeric_state
        entity_id: sensor.temperatura
        below: input_number.temperatura_alvo
        above: '0'
      sequence:
      - action: switch.turn_off
        metadata: {}
        data: {}
        target:
          entity_id: switch.climatizacao
  mode: single
